### ISSUE TITLE
Truncated callsign suffixes extracted from FT8 13-char Free-Text reported to PSKreporter

### ISSUE THREAD

**Issue by brianmathews** [alexranaldi/CWSL_DIGI#6]
I am the author of the SOTA/POTA spotting service SOTAmat (https://SOTAmat.com).  The system works by having SOTA/POTA operators, in the field without cell service, send special FT8 messages addressed to themselves where their callsign has up to a 4 character suffix (the suffixes are carefully curated NOT to interfere with valid callsign suffix Country Locators, but instead are callsign suffix Indicators).  The Indicator suffixes are commands to be executed by an automated service (self spotting for example, similar to RBNhole, but for SSB and not just CW).  

Until the recent CWSL_DIGI 0.87-alpha/beta, there has only been one SDR skimming software (SparkSDR) that:

- Looks for callsigns inside FT8 "Free Text" messages (the 13-character FT8 mode that allows any message schema-free).  Most other software on the market (besides SparkSDR) only looks for callsigns in the normal FT8 Schemas where the data structure informs the software that it is an actual callsign rather than just free text.  SparkSDR (and now CWSL_DIGI) look for callsigns in the free text schema-free.
- Also grabs callsign suffixes out of the FT8 "Free Text"
- Reports such callsigns+suffixes to PSKreporter.  Note that the WSJT-X software only reports callsigns found in FT8 CQ messages.  Only SparkSDR reports the Free-text ones.
- My SOTAmat software has a direct feed from PSKreporter.  It finds and decodes the special callsign/suffix messages and executes the instructions.  You can see examples here:  [https://SOTAmat.com/activity](https://SOTAmat.com/activity)

If you want to get into the weeds on how all this works, and the legal framework around it, you can watch a (far too long) video here: https://youtu.be/FG6hO5LgByI

CWSL_DIGI 0.87-alpha/beta has started doing what SparkSDR is doing.  This is AWESOME since the SOTA community wants more SOTAmat compatible skimming stations to hear these messages.

PROBLEM:  While it is great to have CWSL_DIGI add this functionality, it has a bug.  Most of the time it works just like SparkSDR.  However, some of the time CWSL_DIGI is truncating the callsign suffix and removing a character or two.  This completely changes the meaning of the command the user wants to execute!  I have had to black-list any PSKreporter reception reports from CWSL_DIGI until we get this fixed.  What is really strange is that sometimes multiple CWSL_DIGI stations will hear the same FT8 Free-Text message and they will each decode the message differently (one will not truncate the suffix, while the other one does truncate).  Since FT8 has error detection and correction, both stations must be getting the same identical message, but even the same version of the code at two skimmers are reporting different suffixes.  Non-deterministic errors!

You can reach me at S O T A m a t -AT- S O T A m a t -DOT- c o m  and I can share screenshots of the database dump of past reception reports where SparkSDR and most of the CWSL_DIGI reception reports are identical, but some differ and are truncated.

Here is a Google Spreadsheet that is an excerpt of my database showing in Red Color the errors: 
https://docs.google.com/spreadsheets/d/1o5OB-0nNljfd-8szrk1ChgU0ai8c4flRNrE9D4iqHE0/edit?usp=sharing

Thanks!  73 de AB6D - Brian

**Comment by alexranaldi** [comment]
CWSL_DIGI v0.88 will (finally) be released soon. I have no idea what's causing this bug to be honest, but I have modified some of the callsign handling code. Let's see if it's any better with 0.88. There should be a few stations using it as of today. Keep me updated - if this doesn't fix it I will dig deeper.

**Comment by alexranaldi** [comment]
0.88 was released this morning - hopefully this is now resolved!

**Comment by brianmathews** [comment]
Working great.  There are now lots of good SOTAmat reports flowing through the CWSL_DIGI v0.88 network of skimmers!  This will increase the worldwide number of skimmers by 30%!
