### ISSUE TITLE
WSPRnet changed IP addresses

### ISSUE THREAD

**Issue by madpsy** [alexranaldi/CWSL_DIGI#8]
Heads up - wsprnet.org has changed IP address. I'm unsure why addresses for wsprnet & pskr are hard coded but would suggest using their hostname so such changes don't affect the software in future.

**Comment by azwirko** [comment]
I use DigiSkimmer with another SDR setup and it transitioned the IP address change without issue, while CWSL_Digi is throwing WSPRnet upload errors.

Looking at DigiSkimmer code, line 155 of wsprnet.py they simply use

https://github.com/lazywalker/DigiSkimmer/blob/master/digiskr/wsprnet.py

                resp = s.post("http://wsprnet.org/post",
                              files=postfiles, params=params, timeout=300)

73

andyz - K1RA

**Comment by madpsy** [comment]
I  tried recompiling using a DNS lookup but getting it to build at all has been troublesome, mainly due to weird Qt symbol errors. Exchanged email with Alex and says he'll give it a go when he has time as still has a build environment for it, so fingers crossed.

In the mean time I'll give it another go!

Nathan - MM3NDH

**Comment by dc7ds** [comment]
In the meantime: configure yourself an Ip Alias with the old wsprnet Ip and configure a tcp port forward to the new wsprnet address 😉Gesendet SD mobil Am 11.10.2023 um 08:07 schrieb madpsy ***@***.***>:﻿
I  tried recompiling using a DNS lookup but getting it to build at all has been troublesome, mainly due to weird Qt symbol errors. Exchanged email with Alex and says he'll give it a go when he has time as still has a build environment for it, so fingers crossed.
In the mean time I'll give it another go!

**Comment by madpsy** [comment]
That was going to be plan C (can do it natively in iptables or with socat etc). For now I just disabled wsprnet reporting in the config to stop memory filling up!

**Comment by madpsy** [comment]
Heads up for anyone wanting to try the forwarding method within Windows directly (I've done it on my router directly but same result either way).... 

Run the following in cmd/powershell as Administrator (right click, run as Admin)

`netsh interface portproxy add v4tov4 listenaddress=0.0.0.0 listenport=80 connectaddress=129.80.144.143 connectport=80`

Add the old wsprnet IP address (50.235.87.130/32) to an interface (any interface is fine, though if you have multiple machines you want to add this workaround to then pick an ethernet interface which is local only / on a different L2 network to the others).

![image](https://github.com/alexranaldi/CWSL_DIGI/assets/13963858/cb57ff8f-64d0-4c01-b32a-25e87350d64b)


Test with curl / web browser and ensure you can connect to http://50.235.87.130

![image](https://github.com/alexranaldi/CWSL_DIGI/assets/13963858/7ccb8963-486f-47d0-b539-41643587cb09)

**Comment by dc7ds** [comment]
I’d like to add that you can enable usage of Ip aliases on dhcp interfaces following the procedure here: Add a static IP alias to a DHCP interface on Windows 8 (and above)superuser.com73 Stefan DC7DSGesendet SD mobil Am 11.10.2023 um 09:37 schrieb madpsy ***@***.***>:﻿
Heads up for anyone wanting to try the forwarding method....
Run the following in cmd/powershell as Administrator (right click, run as Admin)
netsh interface portproxy add v4tov4 listenaddress=0.0.0.0 listenport=80 connectaddress=129.80.144.143 connectport=80
Add the old wsprnet IP address (50.235.87.130/32) to an interface (any interface is fine, though if you have multiple machines you want to add this workaround to then pick an ethernet interface which is local only / on a different L2 network to the others).

Test with curl / web browser and ensure you can connect to http://50.235.87.130

**Comment by madpsy** [comment]
Hi Stefan, the link didn't send in your reply so I'll add what I think you're referring to:

`netsh interface ipv4 set interface interface="<name>" dhcpstaticipcoexistence=enabled`
`netsh interface ipv4 add address "<name>" 50.235.87.130 255.255.255.255`

**Comment by dc7ds** [comment]
👍👍Gesendet SD mobil Am 11.10.2023 um 09:50 schrieb madpsy ***@***.***>:﻿
Hi Stefan, the link didn't send in your reply so I'll add what I think you're referring to:
netsh interface ipv4 set interface interface="<name>" dhcpstaticipcoexistence=enabled
netsh interface ipv4 add address "<name>" 50.235.87.130 255.255.255.255

**Comment by azwirko** [comment]
Thanks for the Windows rule, but I opted for a DSTNAT rule at my firewall so any PC attempting will be forwarded to the new address.  For those running MikroTik the rule is

/ip firewall
add action=dst-nat chain=dstnat comment="WSPRnet IP change" dst-address=50.235.87.130 to-addresses=129.80.144.143

73

andyz - K1RA

**Comment by madpsy** [comment]
Good info! I implemented in the core router too but it's an Edgerouter (VyOS based). Could advise if anyone else uses one but my config is very specific due to the multiple different internet connections involved!

**Comment by alexranaldi** [comment]
Fixed in 0.88, to be released soon. Contact me directly if you want to test.

**Comment by alexranaldi** [comment]
Resolved in today's release, v 0.88
